export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RETRIEVE_PRODUCTS = 'RETRIEVE_PRODUCTS'
export const RETRIEVE_PRODUCTS_ERROR = 'RETRIEVE_PRODUCTS_ERROR'

export const REQUEST_SINGLE_PRODUCT = 'REQUEST_SINGLE_PRODUCT'
export const RETRIEVE_SINGLE_PRODUCT = 'RETRIEVE_SINGLE_PRODUCT'
export const RETRIEVE_SINGLE_PRODUCT_ERROR = 'RETRIEVE_SINGLE_PRODUCT_ERROR'

export const REQUEST_PRODUCT_CREATION = 'REQUEST_PRODUCT_CREATION'
export const PRODUCT_CREATION_SUCCESS = 'PRODUCT_CREATION_SUCCESS'
export const PRODUCT_CREATION_ERROR = 'PRODUCT_CREATION_ERROR'
