export const CREATE_USER = 'CREATE_USER';
export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
export const RETRIEVE_CURRENT_USER = 'RETRIEVE_CURRENT_USER';
export const RETRIEVE_ERROR = 'RETRIEVE_ERROR';
export const LOG_IN_USER = "LOG_IN_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const LOG_ERROR = "LOG_ERROR";

