export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const REQUEST_USER_ACTION = 'REQUEST_USER_ACTION';
export const RETRIEVE_ACTION_ERROR = 'RETRIEVE_ACTION_ERROR';


export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
export const RETRIEVE_CURRENT_USER = 'RETRIEVE_CURRENT_USER';
export const RETRIEVE_ERROR = 'RETRIEVE_ERROR';

export const LOG_IN_USER = "LOG_IN_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const LOG_ERROR = "LOG_ERROR";

export const REQUEST_USER_BY_USERNAME = 'REQUEST_USER_BY_USERNAME';
export const RETRIEVE_USER_BY_USERNAME= 'RETRIEVE_USER_BY_USERNAME';

export const REQUEST_USERS_SEARCH = 'REQUEST_USERS_SEARCH';
export const RETRIEVE_USERS_SEARCH = 'RETRIEVE_USERS_SEARCH';
